specVersion: 0.2.0
name: slp-polkadot-subql
version: 1.0.0
description: ''
repository: 'https://github.com/bifrost-finance/slp-kusama-subql.git'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
dataSources:
  - kind: substrate/Runtime
    startBlock: 11930320
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: staking
          kind: substrate/BlockHandler
        - handler: handleStakingErapaid
          kind: substrate/EventHandler
          filter:
            module: staking
            method: EraPaid
        - handler: handleStakingBonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleStakinUnbonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Unbonded
        - handler: handleStakingWithdrawn
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Withdrawn
        - handler: handleStakingPayoutstarte
          kind: substrate/EventHandler
          filter:
            module: staking
            method: PayoutStarted
        - handler: handleRemark
          kind: substrate/EventHandler
          filter:
            module: system
            method: Remarked